#!/usr/bin/env python3
"""The project version: the base from version.h, the commit count, the hash.

    version.py --source <version.h> [--header <revision.h>]

Prints the version. With --header it also writes the generated header that
version.h includes, and only when the text changes, so an unchanged commit
count does not relink anything.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

HEADER = """// Generated by tools/version.py — the revision. Do not edit or commit.
#pragma once

#define BRAAM_REVISION "{rev}"
"""


def base_of(path: Path):
    m = re.search(r'BRAAM_VERSION_BASE\s+"([^"]+)"', path.read_text())
    if not m:
        sys.exit(f"version.py: no BRAAM_VERSION_BASE in {path}")
    return m.group(1)


def git(path: Path, *args):
    """One git command in the repository holding version.h, or None."""
    try:
        r = subprocess.run(["git", *args], cwd=path.resolve().parent,
                           capture_output=True, text=True)
    except OSError:
        return None
    return r.stdout.strip() if r.returncode == 0 else None


def revision(path: Path):
    """Commit count, then the short hash: `24-35f6924`."""
    # No git and no repository — an unpacked release — is revision 0, not an
    # error: the tree still builds, and the base is what identifies it.
    count = git(path, "rev-list", "HEAD", "--count")
    if not count:
        return "0"
    commit = git(path, "log", "-1", "--format=%h")
    return f"{count}-{commit}" if commit else count


def version_of(path: Path):
    return f"{base_of(path)}.{revision(path)}"


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", type=Path, required=True)
    ap.add_argument("--header", type=Path)
    args = ap.parse_args(argv[1:])

    rev = revision(args.source)
    if not args.header:
        print(f"{base_of(args.source)}.{rev}")
        return

    text = HEADER.format(rev=rev)
    if args.header.exists() and args.header.read_text() == text:
        return
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(text)
    print(f"braam {base_of(args.source)}.{rev}")


if __name__ == "__main__":
    main(sys.argv)
